In [1]:
import pandas as pd
import sqlite3

In [3]:
df = pd.read_csv("../data/cleaned/sales_records_enhanced.csv")

df.head()

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Month,Year,Profit Margin,Profit Margin (%),Discount Bucket
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,2012-07-27,443368995,2012-07-28,1593,9.33,6.92,14862.69,11023.56,3839.13,7,2012,0.258307,25.830654,Medium Discount
1,Middle East And North Africa,Morocco,Clothes,Online,M,2013-09-14,667593514,2013-10-19,4611,109.28,35.84,503890.08,165258.24,338631.84,9,2013,0.672035,67.203514,Low Discount
2,Australia And Oceania,Papua New Guinea,Meat,Offline,M,2015-05-15,940995585,2015-06-04,360,421.89,364.69,151880.40,131288.40,20592.00,5,2015,0.135580,13.558036,Medium Discount
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,2017-05-17,880811536,2017-07-02,562,109.28,35.84,61415.36,20142.08,41273.28,5,2017,0.672035,67.203514,Low Discount
4,Europe,Slovakia,Beverages,Offline,L,2016-10-26,174590194,2016-12-04,3973,47.45,31.79,188518.85,126301.67,62217.18,10,2016,0.330032,33.003161,Low Discount

In [4]:
conn = sqlite3.connect("../data/cleaned/dashiq.db")

print("Database created successfully")

Database created successfully

In [5]:
df.to_sql("fact_sales", conn, if_exists="replace", index=False)

print("Table 'fact_sales' created")

Table 'fact_sales' created

In [7]:
# dim_region
df[["Region"]].drop_duplicates().to_sql("dim_region", conn, if_exists="replace", index=False)

# dim_country
df[["Country"]].drop_duplicates().to_sql("dim_country", conn, if_exists="replace", index=False)

# dim_product
df[["Item Type"]].drop_duplicates().to_sql("dim_product", conn, if_exists="replace", index=False)

# dim_channel
df[["Sales Channel"]].drop_duplicates().to_sql("dim_channel", conn, if_exists="replace", index=False)

# dim_priority
df[["Order Priority"]].drop_duplicates().to_sql("dim_priority", conn, if_exists="replace", index=False)

# dim_date
df[["Order Date", "Year", "Month"]].drop_duplicates().to_sql("dim_date", conn, if_exists="replace", index=False)

print("Dimension tables created")

Dimension tables created

In [9]:
cursor = conn.cursor()

cursor.execute("SELECT name FROM sqlite_master WHERE type='table';")
tables = cursor.fetchall()

tables

[('sales_records_enhanced',),
 ('fact_sales',),
 ('dim_region',),
 ('dim_country',),
 ('dim_product',),
 ('dim_channel',),
 ('dim_priority',),
 ('dim_date',)]

In [12]:
pd.read_sql("SELECT * FROM fact_sales LIMIT 10", conn)

,Region,Country,Item Type,Sales Channel,Order Priority,Order Date,Order ID,Ship Date,Units Sold,Unit Price,Unit Cost,Total Revenue,Total Cost,Total Profit,Month,Year,Profit Margin,Profit Margin (%),Discount Bucket
0,Sub-Saharan Africa,South Africa,Fruits,Offline,M,2012-07-27,443368995,2012-07-28,1593,9.33,6.92,14862.69,11023.56,3839.13,7,2012,0.258307,25.830654,Medium Discount
1,Middle East And North Africa,Morocco,Clothes,Online,M,2013-09-14,667593514,2013-10-19,4611,109.28,35.84,503890.08,165258.24,338631.84,9,2013,0.672035,67.203514,Low Discount
2,Australia And Oceania,Papua New Guinea,Meat,Offline,M,2015-05-15,940995585,2015-06-04,360,421.89,364.69,151880.40,131288.40,20592.00,5,2015,0.135580,13.558036,Medium Discount
3,Sub-Saharan Africa,Djibouti,Clothes,Offline,H,2017-05-17,880811536,2017-07-02,562,109.28,35.84,61415.36,20142.08,41273.28,5,2017,0.672035,67.203514,Low Discount
4,Europe,Slovakia,Beverages,Offline,L,2016-10-26,174590194,2016-12-04,3973,47.45,31.79,188518.85,126301.67,62217.18,10,2016,0.330032,33.003161,Low Discount
5,Asia,Sri Lanka,Fruits,Online,L,2011-11-07,830192887,2011-12-18,1379,9.33,6.92,12866.07,9542.68,3323.39,11,2011,0.258307,25.830654,Medium Discount
6,Sub-Saharan Africa,Seychelles,Beverages,Online,M,2013-01-18,425793445,2013-02-16,597,47.45,31.79,28327.65,18978.63,9349.02,1,2013,0.330032,33.003161,Low Discount
7,Sub-Saharan Africa,Tanzania,Beverages,Online,L,2016-11-30,659878194,2017-01-16,1476,47.45,31.79,70036.20,46922.04,23114.16,11,2016,0.330032,33.003161,Low Discount
8,Sub-Saharan Africa,Ghana,Office Supplies,Online,L,2017-03-23,601245963,2017-04-15,896,651.21,524.96,583484.16,470364.16,113120.00,3,2017,0.193870,19.386987,Medium Discount
9,Sub-Saharan Africa,Tanzania,Cosmetics,Offline,L,2016-05-23,739008080,2016-05-24,7768,437.20,263.33,3396169.60,2045547.44,1350622.16,5,2016,0.397690,39.768984,Low Discount

In [14]:
pd.read_sql("SELECT COUNT(*) FROM fact_sales", conn)

   COUNT(*)
0    949991

In [15]:
df.shape

(949991, 19)